### ISSUE TITLE
Fix startup warning "External file changes sync may be slow: File watcher failed to start"

### ISSUE THREAD

**Issue by x80486** [flathub/com.jetbrains.DataGrip#1]
Only happens on `Freedesktop 18.08` (or runtimes based on it). `Freedesktop 1.6` is fine, as well as all the other runtimes based on it.

**Comment by TingPing** [comment]
> (as well as all GNOME ones).

Including 3.30?

**Comment by TingPing** [comment]
GNOME 3.30 is based on 18.08 so that is odd.

**Comment by x80486** [comment]
You were right – I corrected this.

It basically works with `Freedesktop 1.6` (or any runtime based on it), and it does not work when using `Freedesktop 18.08` – or any runtime based on it.

So I guess the are different filesystem restrictions between those versions...or something like that.

**Comment by x80486** [comment]
Nothing to do here; this is going to be fixed either in `freedesktop-sdk`'s [pull request](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/merge_requests/783/) `783` or whenever JetBrains [releases](https://youtrack.jetbrains.com/issue/IDEA-198080/) the runtime version `2019.1`.

**Comment by seyuf** [comment]
Hi @x80486, Im using the version 2019 of ultimate intellij but still facing this issue...
Am i missing something or this should be reopened?

**Comment by seyuf** [comment]
My bad new behavior is causing similar issue i.e https://youtrack.jetbrains.com/issue/IDEA-126491.
Seems to be hard to fix.

**Comment by x80486** [comment]
I don't see this warning anymore. Are you talking about the issue **IDEA-126491** or the one _reported_ here?

**Comment by seyuf** [comment]
Indeed the one here have been fixed nothing to do :+1:  . 
I was mistaking it with IDEA-126491 (which is still open).
